// ============================================================================
// Shared TypeScript interfaces for The Insight Engine
// All packages import types from here — never duplicate type definitions.
// ============================================================================

/** Supported social media platforms */
export type Platform = 'twitter' | 'linkedin';

/** Status of a content item in the pipeline */
export type ContentItemStatus = 'ingested' | 'scored' | 'filtered' | 'processing';

/** Status of a draft content piece */
export type DraftContentStatus = 'pending_approval' | 'approved' | 'rejected';

/** Status of a publishing queue item */
export type PublishingQueueItemStatus = 'queued' | 'publishing' | 'published' | 'failed';

/** Content source type */
export type ContentSource = 'rss' | 'arxiv' | 'twitter';

/** Persona tone options */
export type PersonaTone = 'formal' | 'casual' | 'technical' | 'humorous';

/** Digest schedule options */
export type DigestSchedule = 'daily' | 'twice-daily' | 'weekly';

/** Monitoring interval options */
export type MonitoringInterval = 'hourly' | 'every-6h' | 'daily';

// ============================================================================
// Core Domain Interfaces
// ============================================================================

/**
 * A piece of content ingested from an external source (RSS, arXiv, Twitter).
 * Stored in DynamoDB `ContentItems` table.
 */
export interface ContentItem {
  /** UUID v4 */
  id: string;
  /** Article/tweet title */
  title: string;
  /** Author name(s) */
  author: string;
  /** Original publication date (ISO 8601) */
  publicationDate: string;
  /** URL of the original content — used for deduplication via GSI */
  sourceUrl: string;
  /** Full text or summary of the content */
  fullText: string;
  /** Which source this came from */
  source: ContentSource;
  /** When this item was ingested (ISO 8601) */
  ingestedAt: string;
  /** Whether this item is a duplicate of an existing item */
  isDuplicate: boolean;
  /** Relevance score assigned by the Analyst (0-100) */
  relevanceScore?: number;
  /** Pipeline status */
  status?: ContentItemStatus;
  /** Whether this item is part of a trending topic cluster */
  isTrending?: boolean;
}

/**
 * Relevance score result from the Analyst Lambda.
 */
export interface RelevanceScore {
  /** Score from 0 to 100 */
  score: number;
  /** Reasoning provided by the LLM */
  reasoning: string;
  /** Whether recency decay was applied */
  recencyDecayApplied: boolean;
  /** The raw score before recency decay */
  rawScore: number;
}

/**
 * A "hot take" generated by the Analyst Lambda from a high-scoring ContentItem.
 * Stored in DynamoDB `HotTakes` table.
 */
export interface HotTake {
  /** UUID v4 */
  id: string;
  /** Reference to the parent ContentItem */
  contentItemId: string;
  /** The hot take text */
  text: string;
  /** Word count of the text */
  wordCount: number;
  /** Which variation this is (0 or 1 — we generate 2 per item) */
  variationIndex: number;
  /** When this hot take was created (ISO 8601) */
  createdAt: string;
}

/**
 * Platform-specific draft content generated by the Ghostwriter Lambda.
 * Stored in DynamoDB `DraftContent` table.
 */
export interface DraftContent {
  /** UUID v4 */
  id: string;
  /** Reference to the parent HotTake */
  hotTakeId: string;
  /** Reference to the original ContentItem */
  contentItemId: string;
  /** Target platform */
  platform: Platform;
  /** JSON string of the platform-specific content (tweet thread array or LinkedIn post) */
  content: string;
  /** Approval status */
  status: DraftContentStatus;
  /** When this draft was created (ISO 8601) */
  createdAt: string;
}

/**
 * A digest of pending drafts for human review.
 * Compiled by the Gatekeeper and displayed in the dashboard.
 */
export interface ApprovalDigest {
  /** The original content item */
  contentItem: ContentItem;
  /** The hot take used for generation */
  hotTake: HotTake;
  /** All pending drafts for this content item */
  drafts: DraftContent[];
}

/**
 * An item queued for publishing to a social media platform.
 * Stored in DynamoDB `PublishingQueue` table.
 */
export interface PublishingQueueItem {
  /** UUID v4 */
  id: string;
  /** Reference to the DraftContent being published */
  draftContentId: string;
  /** Reference to the original ContentItem */
  contentItemId: string;
  /** Target platform */
  platform: Platform;
  /** Publishing status */
  status: PublishingQueueItemStatus;
  /** When this item was queued (ISO 8601) */
  queuedAt: string;
  /** When this item was published (ISO 8601) */
  publishedAt?: string;
  /** Platform-specific post ID */
  platformPostId?: string;
  /** URL to the published post on the platform */
  platformPostUrl?: string;
  /** Cognito user id that approved this publish request */
  ownerUserId?: string;
  /** Error message if publishing failed */
  errorMessage?: string;
  /** Number of retry attempts made */
  retryCount?: number;
}

/**
 * OAuth connection for a specific dashboard user and platform.
 * Stored in DynamoDB `SocialConnections` table.
 */
export interface SocialConnection {
  /** Cognito user sub */
  userId: string;
  /** Platform account type */
  platform: Platform;
  /** OAuth access token */
  accessToken: string;
  /** OAuth refresh token */
  refreshToken: string;
  /** Access token expiry time (ISO 8601) */
  expiresAt: string;
  /** Optional platform-native user id */
  platformUserId?: string;
  /** Optional platform-native username */
  platformUsername?: string;
  /** Record creation time */
  connectedAt: string;
  /** Last update time */
  updatedAt: string;
}

// ============================================================================
// Persona Configuration
// ============================================================================

/** Platform-specific preferences for content generation */
export interface PlatformPreferences {
  twitter: {
    /** Maximum number of tweets in a thread */
    maxThreadLength: number;
    /** Whether to include hashtags */
    hashtags: boolean;
    /** Whether to include emoji */
    emoji: boolean;
  };
  linkedin: {
    /** Whether to include hashtags */
    hashtags: boolean;
    /** Whether to include emoji */
    emoji: boolean;
  };
}

/** A hero or enemy figure referenced in persona-driven content */
export interface PersonaFigure {
  name: string;
  description: string;
}

/**
 * The persona configuration file that drives tone, filtering, and content
 * generation across all components. Loaded from S3 at Lambda runtime.
 */
export interface PersonaFile {
  /** Content tone */
  tone: PersonaTone;
  /** Topics the persona is an expert in */
  expertiseTopics: string[];
  /** Thought leaders the persona admires */
  heroes: PersonaFigure[];
  /** Figures the persona disagrees with */
  enemies: PersonaFigure[];
  /** Platform-specific content preferences */
  platformPreferences: PlatformPreferences;
  /** Minimum relevance score (0-100) to proceed with content generation */
  relevanceThreshold: number;
  /** How often to compile and send approval digests */
  digestSchedule: DigestSchedule;
  /** How often the Watchtower checks for new content */
  monitoringInterval: MonitoringInterval;
}

// ============================================================================
// OAuth Token Management
// ============================================================================

/**
 * OAuth 2.0 token set for a social media platform.
 * Stored in AWS SSM Parameter Store as SecureString.
 */
export interface OAuthTokenSet {
  /** The current access token */
  accessToken: string;
  /** The refresh token for obtaining new access tokens */
  refreshToken: string;
  /** When the access token expires (ISO 8601) */
  expiresAt: string;
  /** Which platform this token set belongs to */
  platform: Platform;
}

// ============================================================================
// Configuration
// ============================================================================

/** Application configuration loaded from env vars / SSM */
export interface AppConfig {
  /** AWS region */
  awsRegion: string;
  /** Environment name (dev/prod) */
  environment: string;
  /** DynamoDB table name prefix */
  tablePrefix: string;
  /** SQS queue URLs */
  queues: {
    ingestion: string;
    generation: string;
    publish: string;
  };
  /** S3 bucket names */
  buckets: {
    personaFiles: string;
    lambdaDeployments: string;
  };
  /** SNS topic ARNs */
  topics: {
    adminAlerts: string;
  };
  /** Relevance threshold (0-100) */
  relevanceThreshold: number;
}

// ============================================================================
// Logger
// ============================================================================

/** Log levels */
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

/** Structured log entry shape */
export interface LogEntry {
  timestamp: string;
  level: LogLevel;
  component: string;
  message: string;
  errorDetails?: Record<string, unknown>;
}

// ============================================================================
// History & Search (Phase 8)
// ============================================================================

/** Query parameters for the history search API */
export interface HistoryQueryParams {
  /** Full-text search query */
  topic?: string;
  /** Filter by platform */
  platform?: Platform;
  /** Start date (ISO 8601) */
  from?: string;
  /** End date (ISO 8601) */
  to?: string;
  /** Page number (1-indexed, default 1) */
  page?: number;
  /** Results per page (default 20) */
  limit?: number;
}

/** A single item in history search results */
export interface HistoryItem {
  id: string;
  title: string;
  platform: Platform;
  platformUrl: string;
  publishedAt: string;
  contentItemId: string;
  contentSnippet: string;
}

/** Paginated history search results */
export interface HistoryResult {
  total: number;
  page: number;
  results: HistoryItem[];
}

